## ex00_first_select.ipynb

In [1]:
import pandas as pd
import sqlite3

## Create a connection to the database using the sqlite3 library.

In [2]:
db_path = '../data/checking-logs.sqlite'
connection = sqlite3.connect(db_path)

## Get the schema of the checker table.

In [3]:
query = "PRAGMA table_info(pageviews);"
schema = pd.io.sql.read_sql(query, connection)
display(schema)

   cid      name       type  notnull dflt_value  pk
0    0     index    INTEGER        0       None   0
1    1       uid       TEXT        0       None   0
2    2  datetime  TIMESTAMP        0       None   0

## Get only the first ten rows of the table to see what the table looks like.

In [4]:
query = "SELECT * FROM pageviews LIMIT 10"
first_ten_rows = pd.io.sql.read_sql(query, connection)
display(first_ten_rows)

   index      uid                    datetime
0      0  admin_1  2020-04-17 12:01:08.463179
1      1  admin_1  2020-04-17 12:01:23.743946
2      2  admin_3  2020-04-17 12:17:39.287778
3      3  admin_3  2020-04-17 12:17:40.001768
4      4  admin_1  2020-04-17 12:27:30.646665
5      5  admin_1  2020-04-17 12:35:44.884757
6      6  admin_1  2020-04-17 12:35:52.735016
7      7  admin_3  2020-04-17 12:36:21.401412
8      8  admin_3  2020-04-17 12:36:22.023355
9      9  admin_1  2020-04-17 13:55:19.129243

## Use one query to get the subtable.

In [5]:
query = """
        SELECT
            uid,
            datetime
        FROM pageviews
        WHERE uid LIKE 'user_%'
        ORDER BY uid ASC;
        """
pageviews = pd.io.sql.read_sql(query, connection, index_col='datetime', parse_dates=['datetime'], dtype={'uid': 'object'})
display(pageviews)

                                uid
datetime
2020-04-26 21:53:59.624136   user_1
2020-04-26 22:06:19.478143   user_1
2020-04-26 22:12:09.614497   user_1
2020-04-30 19:29:01.831635   user_1
2020-05-05 20:26:32.894852   user_1
...                             ...
2020-04-29 16:51:21.877630  user_30
2020-05-09 20:30:47.034282  user_30
2020-05-22 11:30:18.368990   user_5
2020-05-21 16:28:28.217529   user_9
2020-05-21 16:36:40.915488   user_9

[987 rows x 1 columns]

## Close the connection to the database.

In [6]:
connection.close()

## review

In [7]:
pageviews.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 987 entries, 2020-04-26 21:53:59.624136 to 2020-05-21 16:36:40.915488
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uid     987 non-null    object
dtypes: object(1)
memory usage: 15.4+ KB