## ex01_subquery.ipynb

In [1]:
import pandas as pd
import sqlite3

## Create a connection to the database using the sqlite3 library.

In [2]:
db_path = "../data/checking-logs.sqlite"
connection = sqlite3.connect(db_path)

## Get the schema of the checker table.

In [3]:
query = "PRAGMA table_info(checker)"
schema = pd.io.sql.read_sql(query, connection)

## Get only the first ten rows of the table to see what the table looks like.

In [4]:
query = "SELECT * FROM checker LIMIT 10;"
first_ten_rows = pd.io.sql.read_sql(query, connection)
display(first_ten_rows)

,index,status,success,timestamp,numTrials,labname,uid
0,0,checking,0,2020-04-16 21:12:50.740474,5,NaN,admin_1
1,1,ready,0,2020-04-16 21:12:54.708365,5,code_rvw,admin_1
2,2,checking,0,2020-04-16 21:46:47.769088,7,NaN,admin_1
3,3,ready,0,2020-04-16 21:46:48.121217,7,lab02,admin_1
4,4,checking,0,2020-04-16 21:53:01.862637,6,code_rvw,admin_1
5,5,ready,0,2020-04-16 21:53:05.373389,6,code_rvw,admin_1
6,6,checking,0,2020-04-17 05:18:51.965864,1,NaN,NaN
7,7,ready,0,2020-04-17 05:19:02.744528,1,project1,user_4
8,8,checking,0,2020-04-17 05:22:35.249331,2,project1,user_4
9,9,ready,1,2020-04-17 05:22:45.549397,2,project1,user_4

## Count how many rows satisfy the following conditions using one query with any number of subqueries.

In [5]:
query = """
        SELECT COUNT(*) AS cnt
        FROM pageviews
        WHERE uid IN (
            SELECT uid
            FROM checker
            WHERE status = 'ready'
              AND numTrials = 1
              AND labname IN ('laba04', 'laba04s', 'laba05', 'laba06', 'laba06s', 'project1')
        );
        """

cnt = pd.io.sql.read_sql(query, connection)
display(cnt)

   cnt
0  985

## Close the connection.

In [6]:
connection.close()